export const pt = {
  home: "Home",
  about: "Sobre",
  projects: "Projetos",
  services: "Serviços",
  contact: "Contato",
  downloadCV: "Baixar Currículo",
  readOnline: "Ler Online",
  heroDescription: "Sou um desenvolvedor web apaixonado por criar interfaces modernas, elegantes e funcionais. Com 3 anos de experiência, domino diversas tecnologias e estou sempre em busca de novos desafios para aprimorar minhas habilidades.",
  getInTouch: "Entrar em Contato",
  experience: "Experiência",
  showMore: "Mostrar Mais",
  showLess: "Mostrar Menos",
  sendMeAnEmail: "Me envie um Email",
  sendMeAWhatsapp: "Me envie um WhatsApp",
  sendMeATelegram: "Me envie um Telegram",
  sendMeADiscord: "Me envie um Discord",
  close: "Fechar",
  hiThere: "Olá! 👋",
  welcomeMessage: "Explore meus projetos e, se gostar deles, me conte um pouco sobre o seu próximo projeto. Aproveite a visita!",
  professionalBackground: "Histórico Profissional",
  ExperienceSummary: {
    techXp: { name: "Experiência em Tecnologia", experienceYears: "3" },
    webDevXp: { name: "Desenvolvimento WEB", experienceYears: "2" },
    services: { name: "Serviços prestados", quantity: "27" }
  },
  experiences: [
    {
      company: 'Mont Capital Asset',
      role: 'Desenvolvedor Full Stack Python',
      startDate: 'Jan 2022',
      endDate: 'Presente',
      description: 'Liderando a equipe de desenvolvimento frontend, com foco na construção de aplicações web escaláveis e de alto desempenho utilizando React e Next.js.',
    },
    {
      company: 'Vitta Group Franchising',
      role: 'Desenvolvedor Web Full Stack',
      startDate: 'Out 2023',
      endDate: 'Abr 2024',
      description: 'Desenvolvi aplicações web responsivas e otimizei interfaces de usuário usando Tailwind CSS e TypeScript.',
    },
  ],
  servicesList: [
    {
      title: "Desenvolvimento Web",
      description: "Construção de sites modernos e responsivos usando as tecnologias web mais recentes.",
      icon: "development",
    },
    {
      title: "Design UI/UX",
      description: "Criação de interfaces intuitivas e bonitas que proporcionam uma experiência de usuário perfeita.",
      icon: "design",
    },
    {
      title: "Desenvolvimento Mobile",
      description: "Criação de aplicativos móveis multiplataforma com React Native.",
      icon: "mobile",
    },
    {
      title: "Desenvolvimento Backend",
      description: "Desenvolvimento de sistemas backend robustos e escaláveis com Node.js, Python, e mais.",
      icon: "database",
    },
  ],
  servicesTitle: "Serviços",
  servicesSubtitle: "O Que Posso Fazer Por Você",
  learnMore: "Saiba Mais",
  projectsList: [
    {
      title: 'Website de Portfólio',
      shortDescription: 'Um website de portfólio pessoal para mostrar minhas habilidades, projetos e experiência.',
      image: '/portfolio-website.png',
      link: 'https://www.myportfolio.com',
    },
    {
      title: 'Plataforma de E-commerce',
      shortDescription: 'Uma plataforma de e-commerce avançada com integração de pagamento, carrinho de compras e autenticação de usuários.',
      image: '/ecommerce-platform.png',
      link: 'https://www.ecommerceplatform.com',
    },
    {
      title: 'App de Gestão de Tarefas',
      shortDescription: 'Um aplicativo de gestão de tarefas para ajudar equipes a organizar seu trabalho e melhorar a produtividade.',
      image: '/task-management-app.png',
      link: 'https://www.taskmanagementapp.com',
    },
    {
      title: 'Painel de Mídias Sociais',
      shortDescription: 'Um painel para gerenciar e analisar contas de mídias sociais com análises em tempo real e agendamento de posts.',
      image: '/social-media-dashboard.png',
      link: 'https://www.socialmediadashboard.com',
    },
    {
      title: 'Site de Listagem Imobiliária',
      shortDescription: 'Uma plataforma para navegar e gerenciar listagens imobiliárias com filtros de pesquisa avançados e detalhes das propriedades.',
      image: '/real-estate-listing.png',
      link: 'https://www.realestatelistingsite.com',
    },
    {
      title: 'App de Rastreamento de Fitness',
      shortDescription: 'Um aplicativo móvel para rastrear atividades físicas, definir metas e monitorar o progresso com integração a dispositivos de saúde.',
      image: '/fitness-tracker-app.png',
      link: 'https://www.fitnesstrackerapp.com',
    },
  ],
  viewProject: "Ver Projeto",
  hoverDescription: "Explore o projeto",
};
