export const pt = {
  about: "Sobre",
  projects: "Projetos",
  contact: "Contato",
  downloadCV: "Baixar Currículo",
  readOnline: "Ler Online",
  heroDescription: "Sou um desenvolvedor web apaixonado por criar interfaces modernas, elegantes e funcionais. Com 3 anos de experiência, domino diversas tecnologias e estou sempre em busca de novos desafios para aprimorar minhas habilidades.",
  getInTouch: "Entrar em Contato",
  experience: "Experiência",
  showMore: "Mostrar Mais",
  showLess: "Mostrar Menos",
  professionalBackground: "Histórico Profissional",
  experiences: [
    {
      company: 'Mont Capital Asset',
      role: 'Desenvolvedor Full Stack Python',
      startDate: 'Jan 2022',
      endDate: 'Presente',
      description: 'Liderando a equipe de desenvolvimento frontend, com foco na construção de aplicações web escaláveis e de alto desempenho utilizando React e Next.js.',
    },
    {
      company: 'Vitta Group Franchising',
      role: 'Desenvolvedor Web Full Stack',
      startDate: 'Out 2023',
      endDate: 'Abr 2024',
      description: 'Desenvolvi aplicações web responsivas e otimizei interfaces de usuário usando Tailwind CSS e TypeScript.',
    },
  ],
  services: [
    {
      title: "Desenvolvimento Web",
      description: "Construção de sites modernos e responsivos usando as tecnologias web mais recentes.",
      icon: "development",
    },
    {
      title: "Design UI/UX",
      description: "Criação de interfaces intuitivas e bonitas que proporcionam uma experiência de usuário perfeita.",
      icon: "design",
    },
    {
      title: "Desenvolvimento Mobile",
      description: "Criação de aplicativos móveis multiplataforma com React Native.",
      icon: "mobile",
    },
    {
      title: "Desenvolvimento Backend",
      description: "Desenvolvimento de sistemas backend robustos e escaláveis com Node.js, Python, e mais.",
      icon: "database",
    },
  ],
  servicesTitle: "Serviços",
  servicesSubtitle: "O Que Posso Fazer Por Você",
  learnMore: "Saiba Mais",
  projectsList: [
    {
      title: 'Website de Portfólio',
      shortDescription: 'Um website de portfólio pessoal para mostrar minhas habilidades, projetos e experiência.',
      image: '/portfolio-website.png',
      link: 'https://www.myportfolio.com',
    },
    {
      title: 'Plataforma de E-commerce',
      shortDescription: 'Uma plataforma de e-commerce avançada com integração de pagamento, carrinho de compras e autenticação de usuários.',
      image: '/ecommerce-platform.png',
      link: 'https://www.ecommerceplatform.com',
    },
    {
      title: 'App de Gestão de Tarefas',
      shortDescription: 'Um aplicativo de gestão de tarefas para ajudar equipes a organizar seu trabalho e melhorar a produtividade.',
      image: '/task-management-app.png',
      link: 'https://www.taskmanagementapp.com',
    },
  ],
  viewProject: "Ver Projeto",
  hoverDescription: "Explore o projeto",
};
